email = "ysicing@ysicing.cloud"
github = "https://github.com/ysicing/devops-handbook"

govcnbeianhao = "äº¬ICPå¤‡17001940å·"
govmoebeianhao = "20212380"

[memos]
  desc = "å°‘å¨å¨"
  url = "https://note.ysicing.cloud"

[umami]
  url = "https://umami.external.ysicing.cloud/script.js"
  id = "4c49e691-9efd-4049-ba15-fac0e5a34ea6"

[reaction]
  url = "https://dz.12306.work"
  custom = "ğŸ‘,thumbs-up;â¤ï¸,love;ğŸ˜,cool;"
  memos = "ğŸ‘,thumbs-up;ğŸ‰,party-popper;ğŸ˜„,smile-face;ğŸ˜,cool;"

[app]
  desc = "ä¸€æ¬¾åˆé€‚çš„è½¯ä»¶ï¼Œåœ¨å·¥ä½œä¸­èƒ½æˆä¸ºå¾ˆå¥½çš„ç”Ÿäº§åŠ›å·¥å…·ï¼Œè®©å·¥ä½œäº‹åŠåŠŸå€ï¼›åœ¨ç”Ÿæ´»ä¸­èƒ½æˆä¸ºå¾ˆå¥½çš„æ¶ˆé£å·¥å…·ï¼Œè®©ç”Ÿæ´»å……æ»¡å¤šå§¿å¤šå½©ã€‚ä»¥ä¸‹ä¸ºæ—¥å¸¸å·¥ä½œç”Ÿæ´»ä¸­æ‰€å¸¸ç”¨ï¼š( 2023-08-21 æ›´æ–° )"

[movies]
  desc = "æ•°æ®æ¥æºè±†ç“£"

[hardware]
  desc = "ä¸€ä»¶ç§°å¿ƒçš„äº§å“ï¼Œä»æ”¶åˆ°åŒ…è£¹é‚£ä¸€åˆ»å°±å¼€å§‹å¿ƒæ½®æ¾æ¹ƒï¼Œåˆ°æ—¥ç§¯æœˆç´¯é€æ­¥æˆä¸ºé è°±çš„ä¼™ä¼´ï¼Œæ—¶åˆ»è®©ä½ çš„å·¥ä½œç”Ÿæ´»å……æ»¡æœŸå¾…ã€‚ä»¥ä¸‹ä¸ºæ­£åœ¨ä½¿ç”¨ä¸­çš„äº§å“ï¼š( 2023-08-21 æ›´æ–° )"
